### ISSUE TITLE
BGT waterbreedte actueel

### ISSUE THREAD

**Issue by wvanesse** [hhnk-git/hhnk-modelbuilder#36]
Wanner gebruikt, waarop gebaseerd, wat is de bron ervan, hoe vaak updaten?

Nu is BGT waterdeel echt uit de BGT, dus misschien door DC breedte laten bepalen.

http://srvota201:8888/tree/05.%20Uitgangsgegevens/Gegevens_watervlakken/00.Scripts

**Comment by Ckerklaan** [comment]
Controle BGT waterbreedte van damo waterbreedte?

**Comment by wvanesse** [comment]
controle, is dit klaar?
