### ISSUE TITLE
New sqlite version

### ISSUE THREAD

**Issue by wvanesse** [hhnk-git/hhnk-modelbuilder#43]
Nieuwe migrate met maar 1 global settings, maar klaar voor switchen modeltype

**Comment by Ckerklaan** [comment]
Welke setting zouden jullie hier willen overhouden.

**Comment by wvanesse** [comment]
Meestal beginnen we met de 0d1d test... maar, we moeten wel uit de modelbuilder halen welke watergangen en manholes connected mogen zijn en welke isolated. Ik weet eerlijk gezegd niet hoe dat werkt in de hhnk plugin en of dit opgepakt wordt als alle watergangen isolated zijn. @wvangerwen?

Anders zou je de 2D test als standaard kunnen instellen.

**Comment by wvanesse** [comment]
wietse wil dat ook

**Comment by Ckerklaan** [comment]
Alright, dus gewoon de 0d1d-test dan?

**Comment by wvanesse** [comment]
nee sorry 2D test als standaard

**Comment by Ckerklaan** [comment]
Done!
